### ISSUE TITLE
Contibute to networked-aframe

### ISSUE THREAD

**Issue by arpu** [Elettrotecnica/aframe-vr#1]
Hey,

would it be possiblet o contribute your aframe multstream video room component as MIT to networked-aframe?

**Comment by Elettrotecnica** [comment]
Hi,

I am not sure what you mean by "contributing". To my undestanding, networked-aframe supports different pluggable backends for audio chat, with Janus being only one of them. For my very less ambitious use case, Janus is the only supported backend.

What I did was basically to massage the javascript from https://janus.conf.meetecho.com/mvideoroomtest.html into an A-Frame component. I believe at networked-aframe they do not need to look at my code to implement multistream audio chat :-) In fact, they might have already, as I know this was discussed at some point, so please get in touch with them first.

If my component can be useful to you, I may consider putting it in a separate repository as a standalone tool that could e.g. be picked up by a CDN. We may also find an agreement on licensing, but I am a bit reluctant to switch to MIT to be honest.

Ciao

Antonio
